homepage_route: "home"
routes:
    home: "Main:home"
    login: "Main:login"
    register: "Main:register"
    logout: "Main:logout"
    tweet : "Main:tweet"
    search: "Main:search"
    settings : "Main:settings"
    profile: "Main:profile"
    update: "Main:update"
    delete: "Main:delete"
    retweet: "Main:retweet"
    like: "Main:like"
 

